### ISSUE TITLE
Add fault injection to README and CI/CD

### ISSUE THREAD

**Issue by dthaler** [microsoft/usersim#37]
Fault injection and leak detection are both supported, but some tasks remain which were done in the ebpf-for-windows project, but not in this repo yet:

- [X] list the environment variables in the README (done in PR #39)
- [X] add leak detection to CI/CD (done in PR #39)
- [ ] add fault injection to CI/CD (done in PR #118)
- [ ] explain how to use the fault injection log in the README (done in PR #118)
