### ISSUE TITLE
Add DLL skeleton wrapping calls to DriverEntry/Unload

### ISSUE THREAD

**Issue by dthaler** [microsoft/usersim#6]
- [X] Add sample driver (fixed in PR #14)
- [X] Add dll skeleton library (fixed in PR #14)
- [x] update readme (fixed in PR #15)
- [x] add a test that runs the sample.dll (fixed in PR #15)
